name: Acquire activation file
on:
  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        run: |
          mkdir -p alf_output
          docker run --rm -v "$PWD/alf_output":/data unityci/editor:ubuntu-2022.3.50f1-base-3 unity-editor -batchmode -nographics -quit -createManualActivationFile /data/unity.alf
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity_activation_file
          path: alf_output/unity.alf
